from django.contrib.auth import views as auth_views
from django.urls import path

from accounts.views import (
    AgentBatchSalePaymentCreateView,
    AgentBatchSaleRequestCreateView,
    AgentManagerDashboardView,
    AgentDriverCreateView,
    AgentDriverDeleteView,
    AgentDriverDetailView,
    AgentDriverListView,
    AgentDriverToggleView,
    AgentDriverUpdateView,
    AgentFleetJsonView,
    AgentFleetView,
    AgentFeedbackView,
    AgentInventoryAdjustmentCreateView,
    AgentInventoryThresholdUpdateView,
    AgentInventoryView,
    AgentOrdersView,
    AgentRefundDecisionView,
    AgentRefundListView,
    AgentRequestDecisionView,
    ApproveRestockRequestView,
    AssignDriverView,
    CompanyRefundDecisionView,
    CompanyVerificationDecisionView,
    CompanyAdminDashboardView,
    CompanyLocationsJsonView,
    CompanyAgentDeleteView,
    CompanyAgentListView,
    CompanyAgentToggleView,
    CompanyAgentUpdateView,
    CreateAgentManagerView,
    CreateAgentView,
    CreateCompanyAdminView,
    CreateCompanyView,
    CreateDriverView,
    CreateDriverUserView,
    CreateRestockRequestView,
    CreateSystemAdminView,
    CustomerAddressCreateView,
    CustomerAddressDeleteView,
    CustomerAddressListView,
    CustomerAddressSetDefaultView,
    CustomerAddressUpdateView,
    CustomerDashboardView,
    CustomerLoginView,
    CustomerNotificationsView,
    CustomerLogoutView,
    DriverAcceptDeliveryView,
    DriverArrivedView,
    DriverCompleteDeliveryView,
    DriverConfirmQRBatchView,
    DriverConfirmQRView,
    DriverDashboardView,
    DriverHistoryView,
    DriverPickedUpView,
    DriverReportIssueView,
    DriverStartDeliveryView,
    MarkNotificationsReadView,
    NotificationsJsonView,
    PendingOrdersJsonView,
    ProfileUpdateView,
    CompanyAIInsightsView,
    CompanyBatchCreateView,
    CompanyBatchDetailView,
    CompanyBatchRecallView,
    CompanyBatchSaleDecisionView,
    CompanyBatchSalePaymentDecisionView,
    CompanyInventoryView,
    CompanyProductCreateView,
    CompanyProductListView,
    CompanyProductStarterSeedView,
    CompanyProductToggleView,
    CompanyProductUpdateView,
    CompanyReportExportView,
    CompanyReportsView,
    RegisterView,
    ResendRegistrationOTPView,
    SystemAnnouncementCreateView,
    SystemAnnouncementListView,
    SystemAuditLogExportView,
    SystemAuditLogListView,
    SystemCompanyListView,
    SystemDashboardView,
    SystemReportExportView,
    SystemReportsView,
    SystemUserBulkActionView,
    SystemUserListView,
    SystemUserPasswordResetView,
    SystemUserUpdateView,
    UpdateCompanyPremiumSettingsView,
    UpdateDriverAvailabilityView,
    UpdateDriverLocationView,
    VerifyRegistrationOTPView,
)

app_name = "accounts"

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("register/verify/", VerifyRegistrationOTPView.as_view(), name="verify_registration"),
    path("register/resend-otp/", ResendRegistrationOTPView.as_view(), name="resend_registration_otp"),
    path("login/", CustomerLoginView.as_view(), name="login"),
    path("logout/", CustomerLogoutView.as_view(), name="logout"),
    path("dashboard/", CustomerDashboardView.as_view(), name="dashboard"),
    path("addresses/", CustomerAddressListView.as_view(), name="addresses"),
    path("addresses/create/", CustomerAddressCreateView.as_view(), name="create_address"),
    path("addresses/<int:pk>/edit/", CustomerAddressUpdateView.as_view(), name="edit_address"),
    path("addresses/<int:pk>/delete/", CustomerAddressDeleteView.as_view(), name="delete_address"),
    path("addresses/<int:pk>/default/", CustomerAddressSetDefaultView.as_view(), name="set_default_address"),
    path("agent/dashboard/", AgentManagerDashboardView.as_view(), name="agent_dashboard"),
    path("agent/drivers/", AgentDriverListView.as_view(), name="agent_drivers"),
    path("agent/drivers/create/", AgentDriverCreateView.as_view(), name="agent_driver_create"),
    path("agent/drivers/<int:pk>/", AgentDriverDetailView.as_view(), name="agent_driver_detail"),
    path("agent/drivers/<int:pk>/edit/", AgentDriverUpdateView.as_view(), name="agent_driver_edit"),
    path("agent/drivers/<int:pk>/toggle/", AgentDriverToggleView.as_view(), name="agent_driver_toggle"),
    path("agent/drivers/<int:pk>/delete/", AgentDriverDeleteView.as_view(), name="agent_driver_delete"),
    path("agent/fleet/", AgentFleetView.as_view(), name="agent_fleet"),
    path("agent/fleet/json/", AgentFleetJsonView.as_view(), name="agent_fleet_json"),
    path("agent/orders/", AgentOrdersView.as_view(), name="agent_orders"),
    path("agent/feedback/", AgentFeedbackView.as_view(), name="agent_feedback"),
    path("agent/inventory/", AgentInventoryView.as_view(), name="agent_inventory"),
    path("agent/inventory/batch-requests/create/", AgentBatchSaleRequestCreateView.as_view(), name="agent_batch_request_create"),
    path("agent/inventory/batch-sales/<int:pk>/payments/create/", AgentBatchSalePaymentCreateView.as_view(), name="agent_batch_payment_create"),
    path("agent/inventory/adjust/", AgentInventoryAdjustmentCreateView.as_view(), name="agent_inventory_adjust"),
    path("agent/inventory/<int:pk>/threshold/", AgentInventoryThresholdUpdateView.as_view(), name="agent_inventory_threshold"),
    path("agent/refunds/", AgentRefundListView.as_view(), name="agent_refunds"),
    path("agent/refunds/<int:pk>/approve/", AgentRefundDecisionView.as_view(action="approve"), name="agent_approve_refund"),
    path("agent/refunds/<int:pk>/reject/", AgentRefundDecisionView.as_view(action="reject"), name="agent_reject_refund"),
    path("agent/refunds/<int:pk>/process/", AgentRefundDecisionView.as_view(action="process"), name="agent_process_refund"),
    path("agent/refunds/<int:pk>/fail/", AgentRefundDecisionView.as_view(action="fail"), name="agent_fail_refund"),
    path("driver/dashboard/", DriverDashboardView.as_view(), name="driver_dashboard"),
    path("driver/history/", DriverHistoryView.as_view(), name="driver_history"),
    path("driver/availability/", UpdateDriverAvailabilityView.as_view(), name="driver_availability"),
    path("company/dashboard/", CompanyAdminDashboardView.as_view(), name="company_dashboard"),
    path("company/locations-json/", CompanyLocationsJsonView.as_view(), name="company_locations_json"),
    path("company/products/", CompanyProductListView.as_view(), name="company_products"),
    path("company/products/create/", CompanyProductCreateView.as_view(), name="company_product_create"),
    path("company/products/seed-starter/", CompanyProductStarterSeedView.as_view(), name="company_product_seed_starter"),
    path("company/products/<int:pk>/edit/", CompanyProductUpdateView.as_view(), name="company_product_edit"),
    path("company/products/<int:pk>/toggle/", CompanyProductToggleView.as_view(), name="company_product_toggle"),
    path("company/agents/", CompanyAgentListView.as_view(), name="company_agents"),
    path("company/agents/<int:pk>/edit/", CompanyAgentUpdateView.as_view(), name="company_agent_edit"),
    path("company/agents/<int:pk>/toggle/", CompanyAgentToggleView.as_view(), name="company_agent_toggle"),
    path("company/agents/<int:pk>/delete/", CompanyAgentDeleteView.as_view(), name="company_agent_delete"),
    path("company/inventory/", CompanyInventoryView.as_view(), name="company_inventory"),
    path("company/inventory/batches/create/", CompanyBatchCreateView.as_view(), name="company_batch_create"),
    path("company/inventory/batches/<int:pk>/", CompanyBatchDetailView.as_view(), name="company_batch_detail"),
    path("company/inventory/batches/<int:pk>/recall/", CompanyBatchRecallView.as_view(), name="company_batch_recall"),
    path(
        "company/inventory/stock-requests/<int:pk>/approve/",
        CompanyBatchSaleDecisionView.as_view(action="approve"),
        name="company_batch_sale_approve",
    ),
    path(
        "company/inventory/stock-requests/<int:pk>/reject/",
        CompanyBatchSaleDecisionView.as_view(action="reject"),
        name="company_batch_sale_reject",
    ),
    path(
        "company/inventory/payments/<int:pk>/confirm/",
        CompanyBatchSalePaymentDecisionView.as_view(action="confirm"),
        name="company_batch_payment_confirm",
    ),
    path(
        "company/inventory/payments/<int:pk>/reject/",
        CompanyBatchSalePaymentDecisionView.as_view(action="reject"),
        name="company_batch_payment_reject",
    ),
    path("company/reports/", CompanyReportsView.as_view(), name="company_reports"),
    path(
        "company/reports/export/<str:export_format>/",
        CompanyReportExportView.as_view(),
        name="company_reports_export",
    ),
    path("company/ai-insights/", CompanyAIInsightsView.as_view(), name="company_ai_insights"),
    path("system/dashboard/", SystemDashboardView.as_view(), name="system_dashboard"),
    path("system/companies/", SystemCompanyListView.as_view(), name="system_companies"),
    path("system/users/", SystemUserListView.as_view(), name="system_users"),
    path("system/users/bulk-action/", SystemUserBulkActionView.as_view(), name="system_users_bulk_action"),
    path("system/users/<int:pk>/edit/", SystemUserUpdateView.as_view(), name="system_user_edit"),
    path("system/users/<int:pk>/send-reset/", SystemUserPasswordResetView.as_view(), name="system_user_send_reset"),
    path("system/audit-logs/", SystemAuditLogListView.as_view(), name="system_audit_logs"),
    path("system/audit-logs/export/", SystemAuditLogExportView.as_view(), name="system_audit_export"),
    path("system/reports/", SystemReportsView.as_view(), name="system_reports"),
    path("system/reports/export/<str:export_format>/", SystemReportExportView.as_view(), name="system_reports_export"),
    path("system/announcements/", SystemAnnouncementListView.as_view(), name="system_announcements"),
    path("system/announcements/create/", SystemAnnouncementCreateView.as_view(), name="system_announcement_create"),
    path("profile/", ProfileUpdateView.as_view(), name="profile"),
    path("notifications/", CustomerNotificationsView.as_view(), name="notifications"),
    path("notifications/mark-read/", MarkNotificationsReadView.as_view(), name="mark_notifications_read"),
    path("notifications/json/", NotificationsJsonView.as_view(), name="notifications_json"),
    path("update-location/", UpdateDriverLocationView.as_view(), name="update_location"),
    path("agent/orders/pending-orders-json/", PendingOrdersJsonView.as_view(), name="pending_orders_json"),
    path("agent/request/<int:pk>/accept/", AgentRequestDecisionView.as_view(action="accept"), name="accept_request"),
    path("agent/request/<int:pk>/reject/", AgentRequestDecisionView.as_view(action="reject"), name="reject_request"),
    path("agent/order/<str:order_number>/assign-driver/", AssignDriverView.as_view(), name="assign_driver"),
    path("agent/restock/create/", CreateRestockRequestView.as_view(), name="create_restock_request"),
    path("driver/order/<str:order_number>/accept/", DriverAcceptDeliveryView.as_view(), name="accept_delivery"),
    path("driver/order/<str:order_number>/picked-up/", DriverPickedUpView.as_view(), name="picked_up_delivery"),
    path("driver/order/<str:order_number>/start/", DriverStartDeliveryView.as_view(), name="start_delivery"),
    path("driver/order/<str:order_number>/arrived/", DriverArrivedView.as_view(), name="arrived_delivery"),
    path("driver/order/<str:order_number>/complete/", DriverCompleteDeliveryView.as_view(), name="complete_delivery"),
    path("driver/order/<str:order_number>/confirm-qr/", DriverConfirmQRView.as_view(), name="confirm_delivery_qr"),
    path("driver/confirm-qr-batch/", DriverConfirmQRBatchView.as_view(), name="confirm_delivery_qr_batch"),
    path("driver/order/<str:order_number>/report-issue/", DriverReportIssueView.as_view(), name="report_delivery_issue"),
    path("company/agent-managers/create/", CreateAgentManagerView.as_view(), name="create_agent_manager"),
    path("company/agents/create/", CreateAgentView.as_view(), name="create_agent"),
    path("company/driver-users/create/", CreateDriverUserView.as_view(), name="create_driver_user"),
    path("company/drivers/create/", CreateDriverView.as_view(), name="create_driver"),
    path("company/premium-settings/", UpdateCompanyPremiumSettingsView.as_view(), name="update_company_premium"),
    path(
        "company/refunds/<int:pk>/approve/",
        CompanyRefundDecisionView.as_view(action="approve"),
        name="approve_refund",
    ),
    path(
        "company/refunds/<int:pk>/process/",
        CompanyRefundDecisionView.as_view(action="process"),
        name="process_refund",
    ),
    path(
        "company/refunds/<int:pk>/fail/",
        CompanyRefundDecisionView.as_view(action="fail"),
        name="fail_refund",
    ),
    path(
        "company/refunds/<int:pk>/reject/",
        CompanyRefundDecisionView.as_view(action="reject"),
        name="reject_refund",
    ),
    path("company/restock/<int:pk>/approve/", ApproveRestockRequestView.as_view(), name="approve_restock"),
    path("system/company-admins/create/", CreateCompanyAdminView.as_view(), name="create_company_admin"),
    path("system/system-admins/create/", CreateSystemAdminView.as_view(), name="create_system_admin"),
    path("system/companies/create/", CreateCompanyView.as_view(), name="create_company"),
    path(
        "system/companies/<int:pk>/verify/",
        CompanyVerificationDecisionView.as_view(action="verify"),
        name="verify_company",
    ),
    path(
        "system/companies/<int:pk>/reject/",
        CompanyVerificationDecisionView.as_view(action="reject"),
        name="reject_company",
    ),
    path(
        "system/companies/<int:pk>/resubmit/",
        CompanyVerificationDecisionView.as_view(action="resubmit"),
        name="resubmit_company",
    ),
    path(
        "system/companies/<int:pk>/suspend/",
        CompanyVerificationDecisionView.as_view(action="suspend"),
        name="suspend_company",
    ),
    path(
        "system/companies/<int:pk>/reactivate/",
        CompanyVerificationDecisionView.as_view(action="reactivate"),
        name="reactivate_company",
    ),
    path(
        "password-change/",
        auth_views.PasswordChangeView.as_view(
            template_name="accounts/password_change.html",
            success_url="/accounts/password-change/done/",
        ),
        name="password_change",
    ),
    path(
        "password-change/done/",
        auth_views.PasswordChangeDoneView.as_view(template_name="accounts/password_change_done.html"),
        name="password_change_done",
    ),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(
            template_name="accounts/password_reset_form.html",
            email_template_name="accounts/password_reset_email.txt",
            subject_template_name="accounts/password_reset_subject.txt",
            success_url="/accounts/password-reset/done/",
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html",
            success_url="/accounts/reset/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/complete/",
        auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html"),
        name="password_reset_complete",
    ),
]
