from django.contrib.auth import views as auth_views
from django.urls import path

from accounts.views import (
    AgentManagerDashboardView,
    AgentRequestDecisionView,
    ApproveRestockRequestView,
    AssignDriverView,
    CompanyRefundDecisionView,
    CompanyVerificationDecisionView,
    CompanyAdminDashboardView,
    CompanyLocationsJsonView,
    CreateAgentManagerView,
    CreateAgentView,
    CreateCompanyAdminView,
    CreateCompanyView,
    CreateDriverView,
    CreateDriverUserView,
    CreateRestockRequestView,
    CreateSystemAdminView,
    CustomerDashboardView,
    CustomerLoginView,
    CustomerLogoutView,
    DriverCompleteDeliveryView,
    DriverDashboardView,
    DriverStartDeliveryView,
    NotificationsJsonView,
    PendingOrdersJsonView,
    ProfileUpdateView,
    RegisterView,
    ResendRegistrationOTPView,
    SystemDashboardView,
    UpdateCompanyPremiumSettingsView,
    UpdateDriverLocationView,
    VerifyRegistrationOTPView,
)

app_name = "accounts"

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("register/verify/", VerifyRegistrationOTPView.as_view(), name="verify_registration"),
    path("register/resend-otp/", ResendRegistrationOTPView.as_view(), name="resend_registration_otp"),
    path("login/", CustomerLoginView.as_view(), name="login"),
    path("logout/", CustomerLogoutView.as_view(), name="logout"),
    path("dashboard/", CustomerDashboardView.as_view(), name="dashboard"),
    path("agent/dashboard/", AgentManagerDashboardView.as_view(), name="agent_dashboard"),
    path("driver/dashboard/", DriverDashboardView.as_view(), name="driver_dashboard"),
    path("company/dashboard/", CompanyAdminDashboardView.as_view(), name="company_dashboard"),
    path("company/locations-json/", CompanyLocationsJsonView.as_view(), name="company_locations_json"),
    path("system/dashboard/", SystemDashboardView.as_view(), name="system_dashboard"),
    path("profile/", ProfileUpdateView.as_view(), name="profile"),
    path("notifications/json/", NotificationsJsonView.as_view(), name="notifications_json"),
    path("update-location/", UpdateDriverLocationView.as_view(), name="update_location"),
    path("agent/orders/pending-orders-json/", PendingOrdersJsonView.as_view(), name="pending_orders_json"),
    path("agent/request/<int:pk>/accept/", AgentRequestDecisionView.as_view(action="accept"), name="accept_request"),
    path("agent/request/<int:pk>/reject/", AgentRequestDecisionView.as_view(action="reject"), name="reject_request"),
    path("agent/order/<str:order_number>/assign-driver/", AssignDriverView.as_view(), name="assign_driver"),
    path("agent/restock/create/", CreateRestockRequestView.as_view(), name="create_restock_request"),
    path("driver/order/<str:order_number>/start/", DriverStartDeliveryView.as_view(), name="start_delivery"),
    path("driver/order/<str:order_number>/complete/", DriverCompleteDeliveryView.as_view(), name="complete_delivery"),
    path("company/agent-managers/create/", CreateAgentManagerView.as_view(), name="create_agent_manager"),
    path("company/agents/create/", CreateAgentView.as_view(), name="create_agent"),
    path("company/driver-users/create/", CreateDriverUserView.as_view(), name="create_driver_user"),
    path("company/drivers/create/", CreateDriverView.as_view(), name="create_driver"),
    path("company/premium-settings/", UpdateCompanyPremiumSettingsView.as_view(), name="update_company_premium"),
    path(
        "company/refunds/<int:pk>/approve/",
        CompanyRefundDecisionView.as_view(action="approve"),
        name="approve_refund",
    ),
    path(
        "company/refunds/<int:pk>/reject/",
        CompanyRefundDecisionView.as_view(action="reject"),
        name="reject_refund",
    ),
    path("company/restock/<int:pk>/approve/", ApproveRestockRequestView.as_view(), name="approve_restock"),
    path("system/company-admins/create/", CreateCompanyAdminView.as_view(), name="create_company_admin"),
    path("system/system-admins/create/", CreateSystemAdminView.as_view(), name="create_system_admin"),
    path("system/companies/create/", CreateCompanyView.as_view(), name="create_company"),
    path(
        "system/companies/<int:pk>/verify/",
        CompanyVerificationDecisionView.as_view(action="verify"),
        name="verify_company",
    ),
    path(
        "system/companies/<int:pk>/reject/",
        CompanyVerificationDecisionView.as_view(action="reject"),
        name="reject_company",
    ),
    path(
        "system/companies/<int:pk>/resubmit/",
        CompanyVerificationDecisionView.as_view(action="resubmit"),
        name="resubmit_company",
    ),
    path(
        "password-change/",
        auth_views.PasswordChangeView.as_view(
            template_name="accounts/password_change.html",
            success_url="/accounts/password-change/done/",
        ),
        name="password_change",
    ),
    path(
        "password-change/done/",
        auth_views.PasswordChangeDoneView.as_view(template_name="accounts/password_change_done.html"),
        name="password_change_done",
    ),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(
            template_name="accounts/password_reset_form.html",
            email_template_name="accounts/password_reset_email.txt",
            subject_template_name="accounts/password_reset_subject.txt",
            success_url="/accounts/password-reset/done/",
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html",
            success_url="/accounts/reset/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/complete/",
        auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html"),
        name="password_reset_complete",
    ),
]
