# Generated by Django 6.0.6 on 2026-06-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('agent_manager', 'Agent Manager'), ('driver', 'Driver'), ('company_admin', 'Company Admin'), ('system_admin', 'System Admin')], default='customer', max_length=30),
        ),
    ]
