# Generated by Django 6.0.6 on 2026-06-07 21:04

import accounts.validators
import django.db.models.deletion
from django.db import migrations, models


def populate_managed_company(apps, schema_editor):
    Company = apps.get_model("catalog", "Company")
    User = apps.get_model("accounts", "User")

    admin_company_map = {}
    for company in Company.objects.exclude(admin_id__isnull=True).order_by("pk"):
        admin_company_map.setdefault(company.admin_id, []).append(company)

    for admin_id, companies in admin_company_map.items():
        admin_user = User.objects.filter(pk=admin_id).first()
        if admin_user is None:
            continue

        primary_company = companies[0]
        if admin_user.managed_company_id is None:
            admin_user.managed_company_id = primary_company.pk
            admin_user.save(update_fields=["managed_company"])

        for extra_company in companies[1:]:
            extra_company.admin_id = None
            extra_company.save(update_fields=["admin"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_failed_login_attempts_user_last_failed_login_at_and_more'),
        ('catalog', '0008_agent_credit_limit_agent_credit_period_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='managed_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_admin_users', to='catalog.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, validators=[accounts.validators.validate_ethiopian_phone_number]),
        ),
        migrations.RunPython(populate_managed_company, migrations.RunPython.noop),
    ]
