# Generated by Django 6.0.6 on 2026-06-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_inventorytransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_label',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
