# Generated by Django 6.0.6 on 2026-06-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_size_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='registration_document',
            field=models.FileField(blank=True, null=True, upload_to='companies/documents/'),
        ),
    ]
