# Generated by Django 6.0.6 on 2026-06-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_company_registration_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('on_delivery', 'On Delivery'), ('off_duty', 'Off Duty')], default='available', max_length=20),
        ),
    ]
