# Generated by Django 6.0.6 on 2026-06-23 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_legacy_approved_sales(apps, schema_editor):
    AgentBatchSale = apps.get_model("catalog", "AgentBatchSale")
    for sale in AgentBatchSale.objects.filter(status="approved", quantity_approved__gt=0):
        if sale.credit_due_date and sale.approved_at:
            approved_at = sale.approved_at
            approved_date = timezone.localtime(approved_at).date() if timezone.is_aware(approved_at) else approved_at.date()
            sale.credit_terms_days = max((sale.credit_due_date - approved_date).days, 1)
        sale.quantity_received = sale.quantity_approved
        sale.status = "received"
        sale.received_at = sale.approved_at or sale.created_at
        sale.received_by_id = sale.approved_by_id
        sale.receipt_note = "Backfilled from legacy approval workflow."
        sale.save(
            update_fields=[
                "credit_terms_days",
                "quantity_received",
                "status",
                "received_at",
                "received_by",
                "receipt_note",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_agent_credit_limit_agent_credit_period_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentbatchsale',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agentbatchsale',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentbatchsale',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_batch_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentbatchsale',
            name='credit_terms_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentbatchsale',
            name='overdue_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentbatchsale',
            name='quantity_received',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentbatchsale',
            name='receipt_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agentbatchsale',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentbatchsale',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_batch_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agentbatchsale',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('received', 'Received'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.RunPython(backfill_legacy_approved_sales, migrations.RunPython.noop),
    ]
