# Generated by Django 6.0.6 on 2026-06-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_agentbatchsale_cancellation_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="overdue_status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=20,
            ),
        ),
    ]
