# Generated by Django 6.0.6 on 2026-07-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_company_maximum_cancellation_period_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='complaint_appeal_period_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='company',
            name='complaint_period_days',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
