# Generated by Django 6.0.6 on 2026-06-06 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_cancellation_deadline_order_discount_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryconfirmation',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryconfirmation',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryconfirmation',
            name='scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_delivery_confirmations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryconfirmation',
            name='qr_token',
            field=models.CharField(editable=False, max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('requested', 'Waiting for Agent Response'), ('rejected', 'Rejected by Agent'), ('payment_pending', 'Accepted - Payment Required'), ('paid', 'Paid - Preparing Delivery'), ('driver_assigned', 'Assigned'), ('driver_accepted', 'Accepted'), ('picked_up', 'Picked Up'), ('out_for_delivery', 'On the Way'), ('arrived', 'Arrived'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('requested', 'Waiting for Agent Response'), ('rejected', 'Rejected by Agent'), ('payment_pending', 'Accepted - Payment Required'), ('paid', 'Paid - Preparing Delivery'), ('driver_assigned', 'Assigned'), ('driver_accepted', 'Accepted'), ('picked_up', 'Picked Up'), ('out_for_delivery', 'On the Way'), ('arrived', 'Arrived'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=30),
        ),
        migrations.CreateModel(
            name='DeliveryIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_type', models.CharField(choices=[('customer_not_found', 'Customer not found'), ('wrong_address', 'Wrong address'), ('traffic_delay', 'Traffic / delay'), ('vehicle_issue', 'Vehicle issue'), ('other', 'Other')], max_length=40)),
                ('description', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_issues', to='orders.order')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_delivery_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
