# Generated by Django 6.0.6 on 2026-06-23 05:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_agent_credit_limit_agent_credit_period_days_and_more'),
        ('orders', '0006_refundrequest_failure_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_order_status_idx'),
        ),
    ]
