# Generated by Django 6.0.6 on 2026-07-17 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_complaint_refundtransaction_and_tracking_logs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='agent_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='agent_responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_responded_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='agent_response_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='agent_response_type',
            field=models.CharField(blank=True, choices=[('accept_responsibility', 'Accept responsibility'), ('dispute', 'Dispute the complaint'), ('additional_information', 'Provide additional information')], max_length=30),
        ),
        migrations.AddField(
            model_name='complaint',
            name='appeal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='appealed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='appealed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appealed_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='company_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='company_decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_decided_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='company_decision_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='system_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='system_decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_decided_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='system_decision_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('submitted', 'Complaint Submitted'), ('awaiting_agent_response', 'Awaiting Agent Response'), ('under_company_review', 'Under Company Review'), ('decision_issued', 'Decision Issued'), ('appeal_submitted', 'Appeal Submitted'), ('under_system_review', 'Under System Review'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='submitted', max_length=30),
        ),
        migrations.AlterField(
            model_name='complaintevidence',
            name='image',
            field=models.FileField(upload_to='orders/complaints/'),
        ),
        migrations.AlterField(
            model_name='complaintstatushistory',
            name='status',
            field=models.CharField(choices=[('submitted', 'Complaint Submitted'), ('awaiting_agent_response', 'Awaiting Agent Response'), ('under_company_review', 'Under Company Review'), ('decision_issued', 'Decision Issued'), ('appeal_submitted', 'Appeal Submitted'), ('under_system_review', 'Under System Review'), ('resolved', 'Resolved'), ('closed', 'Closed')], max_length=30),
        ),
    ]
