# Generated by Django 6.0.6 on 2026-07-17 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_company_complaint_appeal_period_days_and_more"),
        ("orders", "0009_complaint_agent_responded_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderLiveTracking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("recorded_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                ("resumed_at", models.DateTimeField(blank=True, null=True)),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("is_paused", models.BooleanField(default=False)),
                ("last_distance_meters", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("last_eta_minutes", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="live_trackings",
                        to="catalog.driver",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_tracking",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ("-recorded_at", "-updated_at"),
                "indexes": [
                    models.Index(fields=["is_active"], name="ord_live_active_idx"),
                    models.Index(fields=["recorded_at"], name="ord_live_recorded_idx"),
                ],
            },
        ),
    ]
